ARG VERSION

FROM python:${VERSION}

RUN apt-get update

RUN apt-get -y install poppler-utils

WORKDIR /app

ADD . .

#Get requirements for python app
RUN pip install -r requirements.txt

ENTRYPOINT [ "/usr/local/bin/python", "bot.py"]